### PR TITLE
spring-cloud-service-start (alias scs-start)

### PR DESCRIPTION
**Pull request by daniellavoie**
[#149587335]

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@daniellavoie Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=31)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=31) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@daniellavoie Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=31)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=31) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@daniellavoie Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=31)!

**Comment by csterwa** [comment]
This looks simple and good to me.

**Pull request merged**
