### PR TITLE
Include one-liner on installing plugin from cf repo

### PR DESCRIPTION
**Pull request by aegershman**
Convenience for installing the plugin from the cloud foundry plugins repo. Currently we only list how to build/install it from source.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@aegershman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=44)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=44) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@aegershman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/spring-cloud-services-cli-plugin&pullRequestId=44)!

**Comment by scottfrederick** [comment]
@csterwa @fifthposition 

As an alternative, we could add a link to the existing documentation and installation instructions at https://docs.pivotal.io/spring-cloud-services/1-5/common/cf-cli-plugin.html. That way we'd only have to maintain the installation steps in one place.

**Comment by aegershman** [comment]
^That could be even better. Regardless, I think the link would be a nice addition. A few of my coworkers have run into frustrations where they don't realize this plugin is available pre-built from the community repo, and they end up struggling for a while to build the cli from source. I'm sure it happens to other people as well.

**Comment by csterwa** [comment]
We will also add this to our docs for the CLI plugin. Thank you @aegershman.

**Comment by aegershman** [comment]
No worries, and thanks for everything you all do. You're making our lives as developers _objectively_ better.

**Pull request merged**
